version: '3.8'

services:
  repom.api:
    build:
      context: .
      dockerfile: repom.application.api/Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - postgres
      - elasticsearch
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=repom;Username=postgres;Password=postgres
      - ElasticSearch__Uri=http://elasticsearch:9200

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: repom
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

volumes:
  pgdata:
  esdata:
