name: Build and Test .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9'  # Altere para a versão que você está usando

      - name: Restore dependencies
        run: dotnet restore src/repom.galdino.sln

      - name: Build
        run: dotnet build src/repom.galdino.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test src/repom.unittest/repom.unitest.csproj --configuration Release --no-build --logger "trx"
