name: Build and Test .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9'

      - name: Restore dependencies
        run: dotnet restore src/repom.galdino.sln

      - name: Build
        run: dotnet build src/repom.galdino.sln --configuration Release --no-restore

  test:
    runs-on: ubuntu-latest
    needs: build   # <- Só executa se o build passar

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9'

      - name: Restore dependencies
        run: dotnet restore src/repom.galdino.sln

      - name: Run tests
        run: dotnet test src/repom.unitest/repom.unitest.csproj --configuration Release --no-restore --logger "trx"
